version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t denailry/goridepay-driverworker:latest .
      - run: docker push company/app:$CIRCLE_BRANCH
      - run: |
          docker login --email=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com
          docker build --rm=false -t registry.heroku.com/goridepay-driverworker/web .
          docker push registry.heroku.com/goridepay-driverworker/web:latest