version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t denailry/goridepay-driverworker:latest .
  deploy:
    machine: true
    working_directory: ~/Documents/sea/go-project/src/goridepay-driverworker
    environment:
      HEROKU_APP: "goridepay-driverworker"
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            cat >~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine registry.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            EOF
            chmod 600 ~/.netrc
            docker login --username=$HEROKU_EMAIL --password=$HEROKU_API_KEY registry.heroku.com
            docker build --rm=false -t registry.heroku.com/goridepay-driverworker/web .
            heroku container:push release --app goridepay-driverworker

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master